# Generated by Django 3.0.5 on 2020-05-10 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('latitude', models.FloatField(max_length=100)),
                ('longitude', models.FloatField(max_length=100)),
                ('unique_squirrel_id', models.CharField(help_text='\n "Hectare ID" + "Shift" + "Date" + "Hectare Squirrel Number."', max_length=20, primary_key=True, serialize=False, unique=True)),
                ('shift', models.CharField(choices=[('am', 'AM'), ('pm', 'PM')], default='am', max_length=2)),
                ('date', models.DateField()),
                ('age', models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile')], default='adult', max_length=10)),
                ('primary_fur_color', models.CharField(choices=[('Gray', 'Gray'), ('Cinnamon', 'Cinnamon'), ('Black', 'Black'), ('White', 'White')], default='Gray', max_length=10)),
                ('Location', models.CharField(choices=[('GP', 'Ground Plane'), ('AG', 'Above Ground')], default='GP', help_text='the location of where the squirrel was when first sighted.', max_length=20)),
                ('specific_location', models.TextField(blank=True, max_length=500)),
                ('running', models.BooleanField(default=False)),
                ('chasing', models.BooleanField(default=False)),
                ('climbing', models.BooleanField(default=False)),
                ('eating', models.BooleanField(default=False)),
                ('foraging', models.BooleanField(default=False)),
                ('other_activities', models.TextField(blank=True, max_length=500)),
                ('kuks', models.BooleanField(default=False, help_text='\n A squirrel was found qukking.')),
                ('quaas', models.BooleanField(default=False, help_text='\n A squirrel was found quaaing.')),
                ('moans', models.BooleanField(default=False, help_text='\n A squirrel was found moaning.')),
                ('tail_flags', models.BooleanField(default=False, help_text='\n A squirrel was seen flagging its tail.')),
                ('tail_twitches', models.BooleanField(default=False, help_text='\n A squirrel was seen twitching its tail.')),
                ('approaches', models.BooleanField(default=False, help_text='\n A squirrel was seen approaching human, seeking food.')),
                ('indifferent', models.BooleanField(default=False, help_text='\n A squirrel was indifferent to human beings’ presence.')),
                ('runs_from', models.BooleanField(default=False, help_text='\n A squirrel was seen running away.')),
                ('Other_interactions', models.TextField(blank=True, help_text='\n Other types of interactions between squirrels and humans were noticed.', max_length=500)),
            ],
        ),
    ]
